version: '3'

name: pg-transactional-outbox-tests

services:
  postgres-replication:
    image: postgres:14-alpine
    container_name: postgres-replication
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: unless-stopped

volumes:
  postgres-data:
